# Generated by Django 3.1.6 on 2022-04-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='bdate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='contactno',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='fname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='idno',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='mname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='sname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.TextField(default='pending'),
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
