# Generated by Django 3.1.6 on 2022-05-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftsys', '0002_auto_20220419_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='address',
            new_name='add',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='bdate',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='contactno',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='idno',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='specifydisease',
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.TextField(default=''),
        ),
    ]
